# Generated by Django 3.2 on 2021-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_simbathon5', '0003_auto_20210624_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
