# Generated by Django 3.2.4 on 2021-06-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_simbathon5', '0004_alter_faq_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(),
        ),
    ]
